import { useMemo, useState } from 'react'
import { CheckCircle2, FileQuestion, Search, XCircle } from 'lucide-react'
import { topics } from '../data/topics'
import { useAppStore } from '../store/useAppStore'
import { accuracyForTopic, questionCountTopic } from '../lib/analytics'

export function QuestionsPage(){
  const s=useAppStore(x=>x.data),add=useAppStore(x=>x.addQuestionSession)
  const [topicId,setTopicId]=useState(topics.find(t=>t.discipline==='Física')?.id||topics[0].id),[total,setTotal]=useState(10),[correct,setCorrect]=useState(0),[bank,setBank]=useState('FGV'),[year,setYear]=useState(2026),[reason,setReason]=useState('')
  const t=topics.find(x=>x.id===topicId)!,acc=accuracyForTopic(s,topicId),count=questionCountTopic(s,topicId)
  const recent=useMemo(()=>s.questionSessions.slice(0,12),[s.questionSessions])
  const submit=()=>{if(total<=0||correct<0||correct>total)return;add({topicId,total,correct,bank,year,reason});setCorrect(0);setReason('')}
  return <div><div className="page-heading"><div><span className="eyebrow">QUESTÕES</span><h1>Treino conectado aos conteúdos.</h1><p>Registre cada bloco e transforme seus erros em dados úteis de evolução.</p></div></div><div className="question-grid"><section className="panel form-panel"><div className="panel-title"><div><span className="eyebrow">NOVO BLOCO</span><h3>Registrar questões</h3></div><FileQuestion/></div><label>Conteúdo<select value={topicId} onChange={e=>setTopicId(e.target.value)}>{topics.map(x=><option key={x.id} value={x.id}>{x.discipline} — {x.title}</option>)}</select></label><div className="form-2"><label>Total<input type="number" min={1} value={total} onChange={e=>setTotal(+e.target.value)}/></label><label>Acertos<input type="number" min={0} max={total} value={correct} onChange={e=>setCorrect(+e.target.value)}/></label><label>Banca<input value={bank} onChange={e=>setBank(e.target.value)}/></label><label>Ano<input type="number" value={year} onChange={e=>setYear(+e.target.value)}/></label></div><label>Se houve erros, qual foi a principal causa?<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Não registrar causa agora</option><option>Erro conceitual</option><option>Erro de cálculo</option><option>Interpretação</option><option>Fórmula esquecida</option><option>Distração</option></select></label><button className="cta full" onClick={submit}>Salvar bloco de questões</button></section><aside className="panel topic-performance"><span className="eyebrow">DESEMPENHO DO CONTEÚDO</span><h2>{t.title}</h2><div className="topic-big-stats"><div><strong>{count}</strong><small>questões</small></div><div><strong>{acc===null?'—':`${acc}%`}</strong><small>acertos</small></div><div><strong>{s.errors.filter(e=>e.topicId===topicId&&!e.resolved).length}</strong><small>erros abertos</small></div></div><p>O aplicativo usa esses registros para alimentar os gráficos, o mapa de conteúdos e suas recomendações.</p></aside></div><article className="panel" style={{marginTop:16}}><div className="panel-title"><div><span className="eyebrow">HISTÓRICO RECENTE</span><h3>Últimos blocos</h3></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Conteúdo</th><th>Banca</th><th>Questões</th><th>Acertos</th><th>Resultado</th></tr></thead><tbody>{recent.map(q=><tr key={q.id}><td>{q.date}</td><td>{q.topicTitle}</td><td>{q.bank||'—'}</td><td>{q.total}</td><td>{q.correct}</td><td><span className={`result-chip ${q.accuracy>=70?'good':'warn'}`}>{q.accuracy>=70?<CheckCircle2 size={13}/>:<XCircle size={13}/>} {q.accuracy}%</span></td></tr>)}</tbody></table></div>{!recent.length&&<div className="empty-state">Nenhum bloco de questões registrado ainda.</div>}</article></div>
}
